name: Notificar Discord quando nova issue for criada

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"📬 Nova issue criada por **${{ github.actor }}**:\n**${{ github.event.issue.title }}**\n🔗 ${{ github.event.issue.html_url }}\"}" \
          $DISCORD_WEBHOOK
